/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const InteractionsList: core.serialization.ObjectSchema<serializers.InteractionsList.Raw, Proficient.InteractionsList>;
export declare namespace InteractionsList {
    interface Raw {
        data: serializers.Interaction.Raw[];
        has_more: serializers.PaginationHasMore.Raw;
    }
}
