/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ProficientAiApi } from "../../../..";
import * as core from "../../../../core";
export declare const InteractionsList: core.serialization.ObjectSchema<serializers.InteractionsList.Raw, ProficientAiApi.InteractionsList>;
export declare namespace InteractionsList {
    interface Raw {
        data: serializers.Interaction.Raw[];
    }
}
