/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { Proficient } from "../../../..";
/**
 * The data with which an agent is updated.
 */
export interface AgentUpdateParams {
    name?: Proficient.AgentName;
    description?: Proficient.AgentDescription;
}
