/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { Proficient } from "../../../..";
/**
 * The data with which an agent is updated.
 */
export interface AgentUpdateParams {
    description?: Proficient.AgentDescription;
    displayDescription?: Proficient.AgentDisplayDescription;
    displayName?: Proficient.AgentDisplayName;
    name?: Proficient.AgentName;
}
