/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { Proficient } from "../../../..";
/**
 * The data with which an agent is created.
 */
export interface AgentCreateParams {
    name?: Proficient.AgentName;
    description?: Proficient.AgentDescription;
    provider: Proficient.Provider;
    systemMessage?: Proficient.SystemMessage;
    initialTurn?: Proficient.InitialTurn;
}
