/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * The data with which a reply to a message is asked for.
 */
export interface MessageAskParams {
    interactionId: ProficientAiApi.InteractionId;
}
