/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * <p>Each interaction holds a number of <i>messages</i> and every message belongs to an interaction. The `sent_by` property of a message indicates whether a message was created by an agent or a user.</p>
 *
 * @example
 *     {
 *         id: "msg_BlzvLJ8h2QZY8QOK3vjhIlqK43zciPzpPgIhvTo8ai2VnQIW",
 *         object: ProficientAiApi.MessageObjectType.Message,
 *         content: "Tell me some interesting facts about Archimedes.",
 *         createdAt: 1671631795145,
 *         depth: 11,
 *         interactionId: "int_53mfKtX0Da6zaJCp5bNnzxDaEg1xptWvQDr2",
 *         parentId: "msg_BlzvLJ8h2QZY8QOK3vjhIlqK43zciPzpPgIhvTo8ai2VnQIW",
 *         sentBy: ProficientAiApi.InteractionParticipant.User
 *     }
 */
export interface Message {
    id: ProficientAiApi.MessageId;
    object: ProficientAiApi.MessageObjectType;
    content: ProficientAiApi.MessageContent;
    createdAt: ProficientAiApi.CreatedAt;
    depth: ProficientAiApi.MessageDepth;
    interactionId: ProficientAiApi.InteractionId;
    parentId?: ProficientAiApi.MessageParentId | undefined;
    sentBy: ProficientAiApi.InteractionParticipant;
}
