/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * The data with which a message is created.
 */
export interface MessageCreateParams {
    interactionId: ProficientAiApi.InteractionId;
    content: ProficientAiApi.MessageContent;
    parentId?: string;
}
