/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of the `Message` object
 *
 * @example
 *     ProficientAiApi.MessageObjectType.Message
 */
export declare type MessageObjectType = "message";
export declare const MessageObjectType: {
    readonly Message: "message";
};
