/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const AgentConfigUpdateParams: core.serialization.ObjectSchema<serializers.AgentConfigUpdateParams.Raw, Proficient.AgentConfigUpdateParams>;
export declare namespace AgentConfigUpdateParams {
    interface Raw {
        anthropic?: serializers.AnthropicConfig.Raw | null;
        greeting_message?: serializers.GreetingMessage.Raw | null;
        initial_turn?: serializers.InitialTurn.Raw | null;
        model?: serializers.Model.Raw | null;
        openai?: serializers.OpenAiConfig.Raw | null;
        system_message?: serializers.SystemMessage.Raw | null;
    }
}
