/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const AnthropicConfig: core.serialization.ObjectSchema<serializers.AnthropicConfig.Raw, Proficient.AnthropicConfig>;
export declare namespace AnthropicConfig {
    interface Raw {
        temperature?: serializers.AnthropicConfigTemperature.Raw | null;
        top_k?: serializers.AnthropicConfigTopK.Raw | null;
        top_p?: serializers.AnthropicConfigTopP.Raw | null;
    }
}
