/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const OpenAiConfigTemperature: core.serialization.Schema<serializers.OpenAiConfigTemperature.Raw, Proficient.OpenAiConfigTemperature>;
export declare namespace OpenAiConfigTemperature {
    type Raw = number;
}
