/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import { ProficientAiApi } from "../../../..";
export declare namespace Agents {
    interface Options {
        environment: environments.ProficientAiApiEnvironment | string;
        xProficientApiKey: string;
        xProficientUserExternalId: string;
        xProficientUserHmac?: string;
    }
}
export declare class Agents {
    private readonly options;
    constructor(options: Agents.Options);
    /**
     * Returns a list of your agents. The agents are returned sorted by creation date, with the most recently created agents appearing first.
     */
    list(): Promise<ProficientAiApi.AgentsList>;
    /**
     * Retrieves the agent with the given ID.
     */
    get(agentId: ProficientAiApi.AgentId): Promise<ProficientAiApi.Agent>;
}
