/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const CreatedAt: core.serialization.Schema<serializers.CreatedAt.Raw, Proficient.CreatedAt>;
export declare namespace CreatedAt {
    type Raw = number;
}
