/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * <p>Users communicate with agents via <i>interactions</i>. You can think of each interaction as a conversation between an agent and user.</p>
 *
 * @example
 *     {
 *         id: "int_53mfKtX0Da6zaJCp5bNnzxDaEg1xptWvQDr2",
 *         object: ProficientAiApi.InteractionObjectType.Interaction,
 *         agentId: "ag_Lad8YCGGiDLiqIZPWRXmc2ix",
 *         archived: false,
 *         createdAt: 1671631795145,
 *         name: "interaction",
 *         totalMessageCount: 23,
 *         updatedAt: 1671631799692,
 *         userId: "u_1eRoyubdUqWifFiTREaLcvh6"
 *     }
 */
export interface Interaction {
    id: ProficientAiApi.InteractionId;
    object: ProficientAiApi.InteractionObjectType;
    agentId: ProficientAiApi.AgentId;
    archived: ProficientAiApi.InteractionArchived;
    createdAt: ProficientAiApi.CreatedAt;
    name: ProficientAiApi.InteractionName;
    totalMessageCount: ProficientAiApi.InteractionTotalMessageCount;
    updatedAt: ProficientAiApi.UpdatedAt;
    userId: ProficientAiApi.UserId;
}
