/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * The data with which an interaction is created.
 */
export interface InteractionCreateParams {
    agentId: ProficientAiApi.AgentId;
}
