/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of the `Interaction` object
 *
 * @example
 *     ProficientAiApi.InteractionObjectType.Interaction
 */
export declare type InteractionObjectType = "interaction";
export declare const InteractionObjectType: {
    readonly Interaction: "interaction";
};
