/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../../../errors";
import * as ProficientAiApi from "../../..";
import express from "express";
export declare class ServiceUnavailableError extends errors.ProficientAiApiError {
    private readonly body;
    constructor(body: ProficientAiApi.ApiError);
    send(res: express.Response): Promise<void>;
}
