/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import { Agents } from "./api/resources/agents/client/Client";
import { Interactions } from "./api/resources/interactions/client/Client";
import { Messages } from "./api/resources/messages/client/Client";
import { Users } from "./api/resources/users/client/Client";
export declare namespace ProficientClient {
    interface Options {
        environment: core.Supplier<environments.ProficientEnvironment | string>;
        secretKey?: core.Supplier<string | undefined>;
        xProficientApiKey?: core.Supplier<string | undefined>;
        xProficientUserExternalId?: core.Supplier<string | undefined>;
        xProficientUserHmac?: core.Supplier<string | undefined>;
    }
}
export declare class ProficientClient {
    protected readonly options: ProficientClient.Options;
    constructor(options: ProficientClient.Options);
    protected _agents: Agents | undefined;
    get agents(): Agents;
    protected _interactions: Interactions | undefined;
    get interactions(): Interactions;
    protected _messages: Messages | undefined;
    get messages(): Messages;
    protected _users: Users | undefined;
    get users(): Users;
}
