"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProficientAiApiEnvironment = void 0;
exports.ProficientAiApiEnvironment = {
    /**
     * The production environment
     */
    Production: "https://api.proficientai.com",
    /**
     * The staging environment
     */
    Staging: "https://staging.proficientai.com",
    /**
     * The local environment
     */
    Development: "http://localhost:8080/client",
};
