/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const MessageParentId: core.serialization.Schema<serializers.MessageParentId.Raw, ProficientAiApi.MessageParentId>;
export declare namespace MessageParentId {
    type Raw = string | null | undefined;
}
