/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const MessageCreateParams: core.serialization.ObjectSchema<serializers.MessageCreateParams.Raw, ProficientAiApi.MessageCreateParams>;
export declare namespace MessageCreateParams {
    interface Raw {
        interaction_id: serializers.InteractionId.Raw;
        content: serializers.MessageContent.Raw;
        parent_id?: string | null;
    }
}
