/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const MessageObjectType: core.serialization.Schema<serializers.MessageObjectType.Raw, ProficientAiApi.MessageObjectType>;
export declare namespace MessageObjectType {
    type Raw = "message";
}
