/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ProficientAiApi } from "../../../..";
import * as core from "../../../../core";
export declare const AgentId: core.serialization.Schema<serializers.AgentId.Raw, ProficientAiApi.AgentId>;
export declare namespace AgentId {
    type Raw = string;
}
