/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ProficientAiApi } from "../../../..";
import * as core from "../../../../core";
export declare const InteractionCreateParams: core.serialization.Schema<serializers.InteractionCreateParams.Raw, ProficientAiApi.InteractionCreateParams>;
export declare namespace InteractionCreateParams {
    type Raw = serializers.AgentId.Raw;
}
