/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ProficientAiApi } from "../../../..";
import * as core from "../../../../core";
export declare const InteractionCreateResponse: core.serialization.ObjectSchema<serializers.InteractionCreateResponse.Raw, ProficientAiApi.InteractionCreateResponse>;
export declare namespace InteractionCreateResponse {
    interface Raw {
        interaction: serializers.Interaction.Raw;
    }
}
