/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const PaginationLimit: core.serialization.Schema<serializers.PaginationLimit.Raw, Proficient.PaginationLimit>;
export declare namespace PaginationLimit {
    type Raw = string | null | undefined;
}
