/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ProficientAiApi } from "../../../..";
import * as core from "../../../../core";
export declare const PaginationLimit: core.serialization.Schema<serializers.PaginationLimit.Raw, ProficientAiApi.PaginationLimit>;
export declare namespace PaginationLimit {
    type Raw = number | null | undefined;
}
