/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of the `AgentConfig` object
 *
 * @example
 *     ProficientAiApi.AgentConfigObjectType.AgentConfig
 */
export declare type AgentConfigObjectType = "agent_config";
export declare const AgentConfigObjectType: {
    readonly AgentConfig: "agent_config";
};
