/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * Represents the current configuration of the agent. This is an admin-level resource that is not exposed to the users.
 *
 * @example
 *     {
 *         object: ProficientAiApi.AgentConfigObjectType.AgentConfig,
 *         anthropic: {
 *             temperature: 0.8,
 *             topK: 10
 *         },
 *         agentId: "ag_Lad8YCGGiDLiqIZPWRXmc2ix",
 *         greetingMessage: "Hello {{user.first_name}}. How may I help you today?",
 *         initialTurn: ProficientAiApi.InteractionParticipant.User,
 *         model: ProficientAiApi.Model.OpenaiGpt4,
 *         openai: {
 *             frequencyPenalty: 1.2,
 *             presencePenalty: 0.7,
 *             temperature: 0.9
 *         },
 *         systemMessage: "Your name is {{agent.display_name}}. You are an AI assistant developed by Acme Inc. and your job is to help their user {{user.first_name}} with a wide range of tasks."
 *     }
 */
export interface AgentConfig {
    object: ProficientAiApi.AgentConfigObjectType;
    anthropic: ProficientAiApi.AnthropicConfig;
    agentId: ProficientAiApi.AgentId;
    greetingMessage: ProficientAiApi.GreetingMessage;
    initialTurn: ProficientAiApi.InitialTurn;
    model: ProficientAiApi.Model;
    openai: ProficientAiApi.OpenAiConfig;
    systemMessage: ProficientAiApi.SystemMessage;
}
