/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * <p>Only sample from the top K options for each subsequent token. Used to remove "long tail" low probability responses. Defaults to -1, which disables it. See original <a href="https://console.anthropic.com/docs/api/reference">definition</a>. See <a href="https://towardsdatascience.com/how-to-sample-from-language-models-682bceb97277">technical details</a>.</p>
 *
 * @example
 *     10
 */
export declare type AnthropicConfigTopK = number;
