/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * Indicates who sends the first message in each interaction. Defaults to `"user"`.
 *
 * @example
 *     ProficientAiApi.InteractionParticipant.User
 */
export declare type InitialTurn = ProficientAiApi.InteractionParticipant;
