/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * The configuration that is applied to OpenAI models.
 *
 * @example
 *     {
 *         frequencyPenalty: 1.2,
 *         presencePenalty: 0.7,
 *         temperature: 0.9
 *     }
 */
export interface OpenAiConfig {
    frequencyPenalty?: ProficientAiApi.OpenAiConfigFrequencyPenalty;
    presencePenalty?: ProficientAiApi.OpenAiConfigPresencePenalty;
    temperature?: ProficientAiApi.OpenAiConfigTemperature;
    topP?: ProficientAiApi.OpenAiConfigTopP;
}
