/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * <p>Can take values between -2.0 and 2.0, with positive values penalizing the model for generating new tokens that have already appeared frequently in the generated text so far. This reduces the likelihood of the model repeating the same line or phrase verbatim. In essence, a higher positive value for <code>frequency_penalty</code> encourages the model to use less frequently used tokens in the generated text. See original <a href="https://platform.openai.com/docs/api-reference/completions/create#completions/create-frequency_penalty">definition</a>.</p>
 *
 * @example
 *     1.2
 */
export declare type OpenAiConfigFrequencyPenalty = number;
