"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProficientClient = void 0;
const Client_1 = require("./api/resources/agents/client/Client");
const Client_2 = require("./api/resources/users/client/Client");
class ProficientClient {
    constructor(options) {
        this.options = options;
    }
    get agents() {
        var _a;
        return ((_a = this._agents) !== null && _a !== void 0 ? _a : (this._agents = new Client_1.Agents(this.options)));
    }
    get users() {
        var _a;
        return ((_a = this._users) !== null && _a !== void 0 ? _a : (this._users = new Client_2.Users(this.options)));
    }
}
exports.ProficientClient = ProficientClient;
