/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import { Agents } from "./api/resources/agents/client/Client";
import { Users } from "./api/resources/users/client/Client";
export declare namespace ProficientClient {
    interface Options {
        environment: environments.ProficientEnvironment | string;
        authorization?: core.Supplier<string | undefined>;
        xProficientApiKey?: core.Supplier<string | undefined>;
        xProficientUserExternalId?: core.Supplier<string | undefined>;
        xProficientUserHmac?: core.Supplier<string | undefined>;
    }
}
export declare class ProficientClient {
    private readonly options;
    constructor(options: ProficientClient.Options);
    private _agents;
    get agents(): Agents;
    private _users;
    get users(): Users;
}
