"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProficientEnvironment = void 0;
exports.ProficientEnvironment = {
    /**
     * The production environment
     */
    Production: "https://api.proficientai.com",
    /**
     * The staging environment
     */
    Staging: "https://main-64bxvpctea-uc.a.run.app",
    /**
     * The local environment
     */
    Development: "http://localhost:8080",
};
