/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const ProficientEnvironment: {
    /**
     * The production environment
     */
    readonly Production: "https://api.proficientai.com";
    /**
     * The staging environment
     */
    readonly Staging: "https://main-64bxvpctea-uc.a.run.app";
    /**
     * The local environment
     */
    readonly Development: "http://localhost:8080";
};
export declare type ProficientEnvironment = typeof ProficientEnvironment.Production | typeof ProficientEnvironment.Staging | typeof ProficientEnvironment.Development;
