"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiErrorCode = void 0;
exports.ApiErrorCode = {
    InvalidRequest: "invalid_request",
    InvalidCredentials: "invalid_credentials",
    Forbidden: "forbidden",
    ResourceNotFound: "resource_not_found",
    Conflict: "conflict",
    Unavailable: "unavailable",
    Unknown: "unknown",
};
