/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * Represents the general interface of an API error. The body of every error returned by the API contains `code` and `message` fields.
 */
export interface ApiError {
    error: ProficientAiApi.ApiErrorBody;
}
