/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The time at which the object was last updated, measured in milliseconds since the Unix epoch
 *
 * @example
 *     1671631799692
 */
export declare type UpdatedAt = number;
