/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The agent's public-facing description, meant to be visible to your users.
 *
 * @example
 *     "An AI assistant that helps job seekers with their job applications."
 */
export declare type AgentDisplayDescription = string;
