/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const InteractionArchived: core.serialization.Schema<serializers.InteractionArchived.Raw, ProficientAiApi.InteractionArchived>;
export declare namespace InteractionArchived {
    type Raw = boolean;
}
