/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const InteractionCreateParams: core.serialization.ObjectSchema<serializers.InteractionCreateParams.Raw, ProficientAiApi.InteractionCreateParams>;
export declare namespace InteractionCreateParams {
    interface Raw {
        agent_id: serializers.AgentId.Raw;
    }
}
