/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const InteractionName: core.serialization.Schema<serializers.InteractionName.Raw, ProficientAiApi.InteractionName>;
export declare namespace InteractionName {
    type Raw = string;
}
