/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const InteractionTotalMessageCount: core.serialization.Schema<serializers.InteractionTotalMessageCount.Raw, ProficientAiApi.InteractionTotalMessageCount>;
export declare namespace InteractionTotalMessageCount {
    type Raw = number;
}
