"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentConfigObjectType = void 0;
exports.AgentConfigObjectType = {
    AgentConfig: "agent_config",
};
