/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const UserObjectType: core.serialization.Schema<serializers.UserObjectType.Raw, ProficientAiApi.UserObjectType>;
export declare namespace UserObjectType {
    type Raw = "user";
}
