/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const UserUpdateParams: core.serialization.ObjectSchema<serializers.UserUpdateParams.Raw, ProficientAiApi.UserUpdateParams>;
export declare namespace UserUpdateParams {
    interface Raw {
        first_name?: serializers.UserFirstName.Raw | null;
        last_name?: serializers.UserLastName.Raw | null;
    }
}
