/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const UserExternalId: core.serialization.Schema<serializers.UserExternalId.Raw, ProficientAiApi.UserExternalId>;
export declare namespace UserExternalId {
    type Raw = string;
}
