/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const UserFirstName: core.serialization.Schema<serializers.UserFirstName.Raw, ProficientAiApi.UserFirstName>;
export declare namespace UserFirstName {
    type Raw = string;
}
