/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const UserLastName: core.serialization.Schema<serializers.UserLastName.Raw, ProficientAiApi.UserLastName>;
export declare namespace UserLastName {
    type Raw = string;
}
