/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const User: core.serialization.ObjectSchema<serializers.User.Raw, ProficientAiApi.User>;
export declare namespace User {
    interface Raw {
        id: serializers.UserId.Raw;
        object: serializers.UserObjectType.Raw;
        created_at: serializers.CreatedAt.Raw;
        external_id: serializers.UserExternalId.Raw;
        first_name: serializers.UserFirstName.Raw;
        last_name: serializers.UserLastName.Raw;
        updated_at: serializers.UpdatedAt.Raw;
    }
}
