/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const AnthropicConfigTopK: core.serialization.Schema<serializers.AnthropicConfigTopK.Raw, Proficient.AnthropicConfigTopK>;
export declare namespace AnthropicConfigTopK {
    type Raw = number;
}
