/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const AnthropicConfigTemperature: core.serialization.Schema<serializers.AnthropicConfigTemperature.Raw, Proficient.AnthropicConfigTemperature>;
export declare namespace AnthropicConfigTemperature {
    type Raw = number;
}
