/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const AnthropicConfigTopP: core.serialization.Schema<serializers.AnthropicConfigTopP.Raw, Proficient.AnthropicConfigTopP>;
export declare namespace AnthropicConfigTopP {
    type Raw = number;
}
