/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const InitialTurn: core.serialization.Schema<serializers.InitialTurn.Raw, Proficient.InitialTurn>;
export declare namespace InitialTurn {
    type Raw = serializers.InteractionParticipant.Raw;
}
