/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const Model: core.serialization.Schema<serializers.Model.Raw, Proficient.Model>;
export declare namespace Model {
    type Raw = "anthropic.claude-v1" | "anthropic.claude-v1-100k" | "anthropic.claude-instant-v1" | "anthropic.claude-instant-v1-100k" | "openai.gpt-4" | "openai.gpt-3.5-turbo";
}
