/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const Model: core.serialization.Schema<serializers.Model.Raw, Proficient.Model>;
export declare namespace Model {
    type Raw = "openai.gpt-4" | "openai.gpt-3.5-turbo";
}
