/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const OpenAiConfigFrequencyPenalty: core.serialization.Schema<serializers.OpenAiConfigFrequencyPenalty.Raw, Proficient.OpenAiConfigFrequencyPenalty>;
export declare namespace OpenAiConfigFrequencyPenalty {
    type Raw = number;
}
