/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const OpenAiConfigTopP: core.serialization.Schema<serializers.OpenAiConfigTopP.Raw, Proficient.OpenAiConfigTopP>;
export declare namespace OpenAiConfigTopP {
    type Raw = number;
}
