/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const OpenAiConfigPresencePenalty: core.serialization.Schema<serializers.OpenAiConfigPresencePenalty.Raw, Proficient.OpenAiConfigPresencePenalty>;
export declare namespace OpenAiConfigPresencePenalty {
    type Raw = number;
}
