/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const OpenAiConfig: core.serialization.ObjectSchema<serializers.OpenAiConfig.Raw, Proficient.OpenAiConfig>;
export declare namespace OpenAiConfig {
    interface Raw {
        frequency_penalty?: serializers.OpenAiConfigFrequencyPenalty.Raw | null;
        presence_penalty?: serializers.OpenAiConfigPresencePenalty.Raw | null;
        temperature?: serializers.OpenAiConfigTemperature.Raw | null;
        top_p?: serializers.OpenAiConfigTopP.Raw | null;
    }
}
