/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const SystemMessage: core.serialization.Schema<serializers.SystemMessage.Raw, Proficient.SystemMessage>;
export declare namespace SystemMessage {
    type Raw = string;
}
