openapi: 3.0.1
info:
  title: api
  version: ''
paths:
  /agents:
    get:
      description: >-
        Returns a list of your agents. The agents are returned sorted by
        creation date, with the most recently created agents appearing first.
      operationId: agents_getAgents
      tags:
        - Agents
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agents'
      summary: List all agents
components:
  schemas:
    AgentResourceType:
      type: string
      enum:
        - agent
    Agents:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Agent'
      required:
        - data
    Agent:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the agent
        object:
          $ref: '#/components/schemas/AgentResourceType'
          description: The type of the object
        active:
          type: boolean
          description: >-
            Whether the agent is currently active. If not, all interactions with
            this agent will be blocked.
        name:
          type: string
          description: The name of the agent
        description:
          type: string
          description: The description of the agent
        created_at:
          type: integer
          description: >-
            The time at which the object was created, measured in milliseconds
            since the Unix epoch
        updated_at:
          type: integer
          description: >-
            The time at which the object was last updated, measured in
            milliseconds since the Unix epoch
      required:
        - id
        - object
        - active
        - name
        - description
        - created_at
        - updated_at
  securitySchemes: {}
