/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Proficient from "../../..";
/**
 * The data with which an agent is created.
 */
export interface AgentCreateParams {
    description?: Proficient.AgentDescription;
    displayDescription?: Proficient.AgentDisplayDescription;
    displayName?: Proficient.AgentDisplayName;
    greetingMessage?: Proficient.GreetingMessage;
    initialTurn?: Proficient.InitialTurn;
    model: Proficient.Model;
    name?: Proficient.AgentName;
    openai?: Proficient.OpenAiConfig;
    systemMessage?: Proficient.SystemMessage;
}
