/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../../../errors";
import * as Proficient from "../../..";
export declare class ConflictError extends errors.ProficientError {
    constructor(body: Proficient.ApiError);
}
