/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { Proficient } from "../../../..";
/**
 * The data with which an `AgentConfig` is updated.
 */
export interface AgentConfigUpdateParams {
    greetingMessage?: Proficient.GreetingMessage;
    initialTurn?: Proficient.InitialTurn;
    model?: Proficient.Model;
    openai?: Proficient.OpenAiConfig;
    systemMessage?: Proficient.SystemMessage;
}
