/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { Proficient } from "../../../..";
/**
 * Represents the current configuration of the agent. This is an admin-level resource that is not exposed to the users.
 *
 * @example
 *     {
 *         object: Proficient.AgentConfigObjectType.AgentConfig,
 *         agentId: "ag_Lad8YCGGiDLiqIZPWRXmc2ix",
 *         provider: Proficient.Provider.OpenaiGpt4,
 *         systemMessage: "Your name is {{agent.display_name}}. You are an AI assistant developed by Acme Inc. and your job is to help their user {{user.first_name}} with a wide range of tasks.",
 *         initialTurn: Proficient.InteractionParticipant.User,
 *         greetingMessage: "Hello {{user.first_name}}. How may I help you today?"
 *     }
 */
export interface AgentConfig {
    object: Proficient.AgentConfigObjectType;
    agentId: Proficient.AgentId;
    provider: Proficient.Provider;
    systemMessage: Proficient.SystemMessage;
    initialTurn: Proficient.InitialTurn;
    greetingMessage: Proficient.GreetingMessage;
}
