/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * <p>Determines the level of randomness in the generated output. Can take values between 0 and 1.0, with higher values like 0.8 resulting in more randomness, and lower values like 0.2 making the output more predictable. See original <a href="https://console.anthropic.com/docs/api/reference">definition</a>.</p>
 *
 * @example
 *     0.8
 */
export declare type AnthropicConfigTemperature = number;
