/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * <p>An alternative to the <code>temperature</code> option. Uses a method called nucleus sampling, which involves considering only the tokens with the highest probability mass. It specifies the proportion of the probability mass to consider, with a value of 0.1 indicating that only the tokens comprising the top 10% probability mass will be taken into account. In essence, <code>top_p</code> determines the size of the set of tokens to choose from, based on their probabilities. Defaults to -1, which disables it. See original <a href="https://console.anthropic.com/docs/api/reference">definition</a>.</p>
 *
 * @example
 *     0.1
 */
export declare type AnthropicConfigTopP = number;
