"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Model = void 0;
exports.Model = {
    OpenaiGpt4: "openai.gpt-4",
    OpenaiGpt35Turbo: "openai.gpt-3.5-turbo",
};
