/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The underlying model that powers the agent.
 *
 * @example
 *     Proficient.Model.OpenaiGpt4
 */
export declare type Model = "openai.gpt-4" | "openai.gpt-3.5-turbo";
export declare const Model: {
    readonly OpenaiGpt4: "openai.gpt-4";
    readonly OpenaiGpt35Turbo: "openai.gpt-3.5-turbo";
};
