/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * <p>Determines the level of randomness in the generated output. Can take values between 0 and 2.0, with higher values like 0.8 resulting in more randomness, and lower values like 0.2 making the output more predictable. See original <a href="https://platform.openai.com/docs/api-reference/completions/create#completions/create-temperature">definition</a>.</p>
 *
 * @example
 *     0.9
 */
export declare type OpenAiConfigTemperature = number;
