/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The message used you provide to the agent.
 *
 * @example
 *     "You are a helpful AI assistant developed by Acme, Inc. and your job is to help its users with a wide range of tasks."
 */
export declare type SystemMessage = string;
