/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
export interface InteractionsList {
    data: ProficientAiApi.Interaction[];
    hasMore: ProficientAiApi.PaginationHasMore;
}
