/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const AgentObjectType: core.serialization.Schema<serializers.AgentObjectType.Raw, ProficientAiApi.AgentObjectType>;
export declare namespace AgentObjectType {
    type Raw = "agent";
}
