/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const AgentDisplayDescription: core.serialization.Schema<serializers.AgentDisplayDescription.Raw, ProficientAiApi.AgentDisplayDescription>;
export declare namespace AgentDisplayDescription {
    type Raw = string;
}
