/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const AgentActiveStatus: core.serialization.Schema<serializers.AgentActiveStatus.Raw, ProficientAiApi.AgentActiveStatus>;
export declare namespace AgentActiveStatus {
    type Raw = boolean;
}
