"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProficientAiApiTimeoutError = void 0;
class ProficientAiApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, ProficientAiApiTimeoutError.prototype);
    }
}
exports.ProficientAiApiTimeoutError = ProficientAiApiTimeoutError;
