"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProficientTimeoutError = void 0;
class ProficientTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, ProficientTimeoutError.prototype);
    }
}
exports.ProficientTimeoutError = ProficientTimeoutError;
