/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * The data with which a user is created.
 */
export interface UserCreateParams {
    externalId: ProficientAiApi.UserExternalId;
    firstName?: ProficientAiApi.UserFirstName;
    lastName?: ProficientAiApi.UserLastName;
}
