/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of the `User` object
 *
 * @example
 *     ProficientAiApi.UserObjectType.User
 */
export declare type UserObjectType = "user";
export declare const UserObjectType: {
    readonly User: "user";
};
