/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * <p>Represents a user of your project.</p>
 *
 * @example
 *     {
 *         id: "u_1eRoyubdUqWifFiTREaLcvh6",
 *         object: ProficientAiApi.UserObjectType.User,
 *         createdAt: 1671631795145,
 *         externalId: "gtLIK8ELsHTr0Fajg28Ud9eFpJJ3",
 *         firstName: "John",
 *         lastName: "Appleseed",
 *         updatedAt: 1671631799692
 *     }
 */
export interface User {
    id: ProficientAiApi.UserId;
    object: ProficientAiApi.UserObjectType;
    createdAt: ProficientAiApi.CreatedAt;
    externalId: ProficientAiApi.UserExternalId;
    firstName: ProficientAiApi.UserFirstName;
    lastName: ProficientAiApi.UserLastName;
    updatedAt: ProficientAiApi.UpdatedAt;
}
