/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * The data with which a user is updated.
 */
export interface UserUpdateParams {
    firstName?: ProficientAiApi.UserFirstName;
    lastName?: ProficientAiApi.UserLastName;
}
