/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const AgentsList: core.serialization.ObjectSchema<serializers.AgentsList.Raw, Proficient.AgentsList>;
export declare namespace AgentsList {
    interface Raw {
        data: serializers.Agent.Raw[];
    }
}
