/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ListUsersRequest {
    /**
     * If set to `"false"`, only test users will be returned.
     */
    liveMode?: string;
}
