/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Proficient from "../../../..";
export interface ListUsersRequest {
    /**
     * If set to `false`, only test users will be returned.
     */
    liveMode?: Proficient.UserLiveMode;
}
