/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
import express from "express";
import * as serializers from "../../../../serialization";
export interface UsersServiceMethods {
    list(req: express.Request<never, ProficientAiApi.UsersList, never, never>, res: {
        send: (responseBody: ProficientAiApi.UsersList) => Promise<void>;
        cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
        locals: any;
    }): void | Promise<void>;
    get(req: express.Request<{
        user_id: serializers.UserId.Raw;
    }, ProficientAiApi.User, never, never>, res: {
        send: (responseBody: ProficientAiApi.User) => Promise<void>;
        cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
        locals: any;
    }): void | Promise<void>;
    create(req: express.Request<never, ProficientAiApi.User, ProficientAiApi.UserCreateParams, never>, res: {
        send: (responseBody: ProficientAiApi.User) => Promise<void>;
        cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
        locals: any;
    }): void | Promise<void>;
    update(req: express.Request<{
        user_id: serializers.UserId.Raw;
    }, ProficientAiApi.User, ProficientAiApi.UserUpdateParams, never>, res: {
        send: (responseBody: ProficientAiApi.User) => Promise<void>;
        cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
        locals: any;
    }): void | Promise<void>;
    delete(req: express.Request<{
        user_id: serializers.UserId.Raw;
    }, ProficientAiApi.User, never, never>, res: {
        send: (responseBody: ProficientAiApi.User) => Promise<void>;
        cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
        locals: any;
    }): void | Promise<void>;
}
export declare class UsersService {
    private readonly methods;
    private router;
    constructor(methods: UsersServiceMethods, middleware?: express.RequestHandler[]);
    addMiddleware(handler: express.RequestHandler): this;
    toRouter(): express.Router;
}
