/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The total number of messages in the interaction
 *
 * @example
 *     23
 */
export declare type InteractionTotalMessageCount = number;
