/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { Proficient } from "../../../..";
/**
 * An object that contains the initial interaction data including the `Interaction` object itself and the initial messages associated with it.
 */
export interface InteractionCreateResponse {
    interaction: Proficient.Interaction;
    messages: Proficient.Message[];
}
