/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { Proficient } from "../../../..";
/**
 * The data with which an interaction is updated.
 */
export interface InteractionUpdateParams {
    name?: Proficient.InteractionName;
}
