/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Proficient from "../../..";
/**
 * The data with which an interaction is created.
 */
export interface InteractionCreateParams {
    agentId: Proficient.AgentId;
}
