/**
 * This file was auto-generated by Fern from our API Definition.
 */
import express from "express";
import { AgentsService } from "./api/resources/agents/service/AgentsService";
import { InteractionsService } from "./api/resources/interactions/service/InteractionsService";
import { MessagesService } from "./api/resources/messages/service/MessagesService";
import { UsersService } from "./api/resources/users/service/UsersService";
export declare function register(expressApp: express.Express | express.Router, services: {
    agents: AgentsService;
    interactions: InteractionsService;
    messages: MessagesService;
    users: UsersService;
}): void;
