/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as core from "../../../../core";
export declare const AgentDoesNotExistError: core.serialization.Schema<serializers.AgentDoesNotExistError.Raw, string>;
export declare namespace AgentDoesNotExistError {
    type Raw = string;
}
