/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
export interface MessagesList {
    data: ProficientAiApi.Message[];
    hasMore: ProficientAiApi.PaginationHasMore;
}
