/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { Proficient } from "../../../..";
export interface ApiErrorBody {
    code: Proficient.ApiErrorCode;
    message: string;
}
