/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { ProficientAiApi } from "../../../..";
/**
 * An object that contains the initial interaction data including the `Interaction` object itself and the initial messages associated with it.
 */
export interface InteractionCreateResponse {
    interaction: ProficientAiApi.Interaction;
}
