/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of the Interaction object
 */
export declare type InteractionObjectType = "interaction";
export declare const InteractionObjectType: {
    readonly Interaction: "interaction";
};
