/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { ProficientAiApi } from "../../../..";
/**
 * The data with which an `Interaction`` is created.
 */
export declare type InteractionCreateParams = ProficientAiApi.AgentId;
