/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { ProficientAiApi } from "../../../..";
export interface Interaction {
    id: ProficientAiApi.InteractionId;
    object: ProficientAiApi.InteractionObjectType;
    agentId: ProficientAiApi.AgentId;
    /** Whether the interaction has been archived by the user */
    archived: boolean;
    /** The time at which the object was created, measured in milliseconds since the Unix epoch */
    createdAt: number;
    /** The name of the interaction */
    name: string;
    /** The total number of messages in the interaction */
    totalMessageCount: number;
    /** The time at which the object was last updated, measured in milliseconds since the Unix epoch */
    updatedAt: number;
    /** The unique identifier of the user */
    userId: string;
}
