/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Whether the database has more items after this list. If true, then you can send more paginated requests to exhaust the remaining items.
 */
export declare type PaginationHasMore = boolean;
