/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const Message: core.serialization.ObjectSchema<serializers.Message.Raw, Proficient.Message>;
export declare namespace Message {
    interface Raw {
        id: serializers.MessageId.Raw;
        object: serializers.MessageObjectType.Raw;
        content: serializers.MessageContent.Raw;
        created_at: serializers.CreatedAt.Raw;
        depth: serializers.MessageDepth.Raw;
        interaction_id: serializers.InteractionId.Raw;
        parent_id?: (serializers.MessageParentId.Raw | undefined) | null;
        sent_by: serializers.InteractionParticipant.Raw;
    }
}
