/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const MessageResetParams: core.serialization.ObjectSchema<serializers.MessageResetParams.Raw, Proficient.MessageResetParams>;
export declare namespace MessageResetParams {
    interface Raw {
        interaction_id: serializers.InteractionId.Raw;
        content?: serializers.MessageContent.Raw | null;
    }
}
