/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const MessageParentId: core.serialization.Schema<serializers.MessageParentId.Raw, Proficient.MessageParentId>;
export declare namespace MessageParentId {
    type Raw = string | null | undefined;
}
