/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const MessageDepth: core.serialization.Schema<serializers.MessageDepth.Raw, Proficient.MessageDepth>;
export declare namespace MessageDepth {
    type Raw = number;
}
