/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const MessageCreateParams: core.serialization.ObjectSchema<serializers.MessageCreateParams.Raw, Proficient.MessageCreateParams>;
export declare namespace MessageCreateParams {
    interface Raw {
        interaction_id: serializers.InteractionId.Raw;
        content: serializers.MessageContent.Raw;
        parent_id?: string | null;
    }
}
