/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const MessageContent: core.serialization.Schema<serializers.MessageContent.Raw, Proficient.MessageContent>;
export declare namespace MessageContent {
    type Raw = string;
}
