/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const MessageId: core.serialization.Schema<serializers.MessageId.Raw, Proficient.MessageId>;
export declare namespace MessageId {
    type Raw = string;
}
