/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const PaginationStartingAfter: core.serialization.Schema<serializers.PaginationStartingAfter.Raw, ProficientAiApi.PaginationStartingAfter>;
export declare namespace PaginationStartingAfter {
    type Raw = string | null | undefined;
}
