/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const PaginationHasMore: core.serialization.Schema<serializers.PaginationHasMore.Raw, ProficientAiApi.PaginationHasMore>;
export declare namespace PaginationHasMore {
    type Raw = boolean;
}
