/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const UpdatedAt: core.serialization.Schema<serializers.UpdatedAt.Raw, ProficientAiApi.UpdatedAt>;
export declare namespace UpdatedAt {
    type Raw = number;
}
