/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Proficient from "../../..";
export interface InteractionsList {
    data: Proficient.Interaction[];
    hasMore: Proficient.PaginationHasMore;
}
