/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A string that uniquely identifies the user within your project. Ensure that this is the ID that you use to identify the user in your system e.g. database ID, Firebase Auth ID etc. Failing to do so may cause unexpected bugs and errors in your application.
 *
 * @example
 *     "gtLIK8ELsHTr0Fajg28Ud9eFpJJ3"
 */
export declare type UserExternalId = string;
