/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The unique identifier of the user
 *
 * @example
 *     "u_1eRoyubdUqWifFiTREaLcvh6"
 */
export declare type UserId = string;
