"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserObjectType = void 0;
exports.UserObjectType = {
    User: "user",
};
