/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Whether the user exists in live mode. This will be `false` if the user is a test user.
 *
 * @example
 *     false
 */
export declare type UserLiveMode = boolean;
