/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const InteractionParticipant: core.serialization.Schema<serializers.InteractionParticipant.Raw, Proficient.InteractionParticipant>;
export declare namespace InteractionParticipant {
    type Raw = "user" | "agent";
}
