/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const Interaction: core.serialization.ObjectSchema<serializers.Interaction.Raw, Proficient.Interaction>;
export declare namespace Interaction {
    interface Raw {
        id: serializers.InteractionId.Raw;
        object: serializers.InteractionObjectType.Raw;
        agent_id: serializers.AgentId.Raw;
        archived: serializers.InteractionArchived.Raw;
        created_at: serializers.CreatedAt.Raw;
        name: serializers.InteractionName.Raw;
        total_message_count: serializers.InteractionTotalMessageCount.Raw;
        updated_at: serializers.UpdatedAt.Raw;
        user_id: serializers.UserId.Raw;
    }
}
