/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The description of the agent, intended for developers' reference.
 *
 * @example
 *     "Job application assistant"
 */
export declare type AgentDescription = string;
