/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * The data with which an agent is updated.
 */
export interface AgentUpdateParams {
    description?: ProficientAiApi.AgentDescription;
    displayDescription?: ProficientAiApi.AgentDisplayDescription;
    displayName?: ProficientAiApi.AgentDisplayName;
    name?: ProficientAiApi.AgentName;
}
