/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The unique identifier of the agent
 *
 * @example
 *     "ag_Lad8YCGGiDLiqIZPWRXmc2ix"
 */
export declare type AgentId = string;
