/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * <p>An _agent_ is an AI entity that exists to serve your project's users. Agents are intelligent, configurable and context-aware and can interact with your users via a messaging system enabled by the Proficient API.</p>
 *
 * @example
 *     {
 *         id: "ag_Lad8YCGGiDLiqIZPWRXmc2ix",
 *         object: ProficientAiApi.AgentObjectType.Agent,
 *         active: true,
 *         description: "Job application assistant",
 *         displayDescription: "An AI assistant that helps job seekers with their job applications.",
 *         displayName: "Taya",
 *         name: "Taya",
 *         createdAt: 1671631795145,
 *         updatedAt: 1671631799692
 *     }
 */
export interface Agent {
    id: ProficientAiApi.AgentId;
    object: ProficientAiApi.AgentObjectType;
    active: ProficientAiApi.AgentActiveStatus;
    description: ProficientAiApi.AgentDescription;
    displayDescription: ProficientAiApi.AgentDisplayDescription;
    displayName: ProficientAiApi.AgentDisplayName;
    name: ProficientAiApi.AgentName;
    createdAt: ProficientAiApi.CreatedAt;
    updatedAt: ProficientAiApi.UpdatedAt;
}
