/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of the `Agent` object
 *
 * @example
 *     ProficientAiApi.AgentObjectType.Agent
 */
export declare type AgentObjectType = "agent";
export declare const AgentObjectType: {
    readonly Agent: "agent";
};
