/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
/**
 * The data with which an agent is created.
 */
export interface AgentCreateParams {
    description?: ProficientAiApi.AgentDescription;
    displayDescription?: ProficientAiApi.AgentDisplayDescription;
    displayName?: ProficientAiApi.AgentDisplayName;
    greetingMessage?: ProficientAiApi.GreetingMessage;
    initialTurn?: ProficientAiApi.InitialTurn;
    model: ProficientAiApi.Model;
    name?: ProficientAiApi.AgentName;
    openai?: ProficientAiApi.OpenAiConfig;
    systemMessage?: ProficientAiApi.SystemMessage;
}
