/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The agent's display name, intended to serve as the public-facing name visible to your users.
 *
 * @example
 *     "Taya"
 */
export declare type AgentDisplayName = string;
