/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const UserObjectType: core.serialization.Schema<serializers.UserObjectType.Raw, Proficient.UserObjectType>;
export declare namespace UserObjectType {
    type Raw = "user";
}
