/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The 0-based index of the message. The index represents the position of the message within the interaction, where the first (i.e. the oldest) message will have an index of 0.
 *
 * @example
 *     11
 */
export declare type MessageIndex = number;
