/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The content of the message
 *
 * @example
 *     "Tell me some interesting facts about Archimedes."
 */
export declare type MessageContent = string;
