/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The ID of the message that directly precedes a given message within a particular conversation.
 *
 * @example
 *     "msg_BlzvLJ8h2QZY8QOK3vjhIlqK43zciPzpPgIhvTo8ai2VnQIW"
 */
export declare type MessageParentId = string | undefined;
