/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The depth of the message node in the interaction tree. This will be 0 for all root-level messages that mark the beginning of the interaction and increase as the conversation grows longer.
 *
 * @example
 *     11
 */
export declare type MessageDepth = number;
