/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const AgentName: core.serialization.Schema<serializers.AgentName.Raw, Proficient.AgentName>;
export declare namespace AgentName {
    type Raw = string;
}
