/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const Agent: core.serialization.ObjectSchema<serializers.Agent.Raw, Proficient.Agent>;
export declare namespace Agent {
    interface Raw {
        id: serializers.AgentId.Raw;
        object: serializers.AgentObjectType.Raw;
        active: serializers.AgentActiveStatus.Raw;
        description: serializers.AgentDescription.Raw;
        display_description: serializers.AgentDisplayDescription.Raw;
        display_name: serializers.AgentDisplayName.Raw;
        name: serializers.AgentName.Raw;
        created_at: serializers.CreatedAt.Raw;
        updated_at: serializers.UpdatedAt.Raw;
    }
}
