/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ProficientAiApi from "../../..";
import express from "express";
import * as serializers from "../../../../serialization";
export interface InteractionsServiceMethods {
    list(req: express.Request<never, ProficientAiApi.InteractionsList, never, {
        agent_id?: ProficientAiApi.AgentId;
        limit?: ProficientAiApi.PaginationLimit;
        starting_after?: ProficientAiApi.PaginationStartingAfter;
    }>, res: {
        send: (responseBody: ProficientAiApi.InteractionsList) => Promise<void>;
        cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
        locals: any;
    }): void | Promise<void>;
    get(req: express.Request<{
        interaction_id: serializers.InteractionId.Raw;
    }, ProficientAiApi.Interaction, never, never>, res: {
        send: (responseBody: ProficientAiApi.Interaction) => Promise<void>;
        cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
        locals: any;
    }): void | Promise<void>;
    create(req: express.Request<never, ProficientAiApi.InteractionCreateResponse, ProficientAiApi.InteractionCreateParams, never>, res: {
        send: (responseBody: ProficientAiApi.InteractionCreateResponse) => Promise<void>;
        cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
        locals: any;
    }): void | Promise<void>;
    update(req: express.Request<{
        interaction_id: serializers.InteractionId.Raw;
    }, ProficientAiApi.Interaction, ProficientAiApi.InteractionUpdateParams, never>, res: {
        send: (responseBody: ProficientAiApi.Interaction) => Promise<void>;
        cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
        locals: any;
    }): void | Promise<void>;
    delete(req: express.Request<{
        interaction_id: serializers.InteractionId.Raw;
    }, ProficientAiApi.Interaction, never, never>, res: {
        send: (responseBody: ProficientAiApi.Interaction) => Promise<void>;
        cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
        locals: any;
    }): void | Promise<void>;
}
export declare class InteractionsService {
    private readonly methods;
    private router;
    constructor(methods: InteractionsServiceMethods, middleware?: express.RequestHandler[]);
    addMiddleware(handler: express.RequestHandler): this;
    toRouter(): express.Router;
}
