/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The name of the agent, designed to be visible to developers for internal reference purposes.
 *
 * @example
 *     "Taya"
 */
export declare type AgentName = string;
