/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Whether the agent is currently active. If not, users will not be able to interact with the agent.
 *
 * @example
 *     true
 */
export declare type AgentActiveStatus = boolean;
