/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const InteractionId: core.serialization.Schema<serializers.InteractionId.Raw, Proficient.InteractionId>;
export declare namespace InteractionId {
    type Raw = string;
}
