/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const InteractionObjectType: core.serialization.Schema<serializers.InteractionObjectType.Raw, Proficient.InteractionObjectType>;
export declare namespace InteractionObjectType {
    type Raw = "interaction";
}
