/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Proficient from "../../..";
/**
 * The data with which a user is created.
 */
export interface UserCreateParams {
    externalId: Proficient.UserExternalId;
    firstName?: Proficient.UserFirstName;
    lastName?: Proficient.UserLastName;
}
