/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { Proficient } from "../../../..";
/**
 * The data with which a user is updated.
 */
export interface UserUpdateParams {
    firstName?: Proficient.UserFirstName;
    lastName?: Proficient.UserLastName;
}
