/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const AgentDisplayName: core.serialization.Schema<serializers.AgentDisplayName.Raw, Proficient.AgentDisplayName>;
export declare namespace AgentDisplayName {
    type Raw = string;
}
