/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Proficient from "../../../../api";
import * as core from "../../../../core";
export declare const AgentDescription: core.serialization.Schema<serializers.AgentDescription.Raw, Proficient.AgentDescription>;
export declare namespace AgentDescription {
    type Raw = string;
}
