/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { Proficient } from "../../../..";
import * as core from "../../../../core";
export declare const AgentUpdateParams: core.serialization.ObjectSchema<serializers.AgentUpdateParams.Raw, Proficient.AgentUpdateParams>;
export declare namespace AgentUpdateParams {
    interface Raw {
        name?: serializers.AgentName.Raw | null;
        description?: serializers.AgentDescription.Raw | null;
    }
}
