/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../../../errors";
export declare class InteractionDoesNotExistError extends errors.ProficientAiApiError {
    constructor(body: string);
}
