/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Whether the interaction has been archived by the user
 *
 * @example
 *     false
 */
export declare type InteractionArchived = boolean;
