/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { Proficient } from "../../../..";
/**
 * <p>Represents a user of your project.</p>
 *
 * @example
 *     {
 *         id: "u_1eRoyubdUqWifFiTREaLcvh6",
 *         object: Proficient.UserObjectType.User,
 *         createdAt: 1671631795145,
 *         externalId: "gtLIK8ELsHTr0Fajg28Ud9eFpJJ3",
 *         firstName: "John",
 *         lastName: "Appleseed",
 *         updatedAt: 1671631799692
 *     }
 */
export interface User {
    id: Proficient.UserId;
    object: Proficient.UserObjectType;
    createdAt: Proficient.CreatedAt;
    externalId: Proficient.UserExternalId;
    firstName: Proficient.UserFirstName;
    lastName: Proficient.UserLastName;
    updatedAt: Proficient.UpdatedAt;
}
