/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const AgentConfigObjectType: core.serialization.Schema<serializers.AgentConfigObjectType.Raw, ProficientAiApi.AgentConfigObjectType>;
export declare namespace AgentConfigObjectType {
    type Raw = "agent_config";
}
