/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const AgentConfig: core.serialization.ObjectSchema<serializers.AgentConfig.Raw, ProficientAiApi.AgentConfig>;
export declare namespace AgentConfig {
    interface Raw {
        object: serializers.AgentConfigObjectType.Raw;
        anthropic: serializers.AnthropicConfig.Raw;
        agent_id: serializers.AgentId.Raw;
        greeting_message: serializers.GreetingMessage.Raw;
        initial_turn: serializers.InitialTurn.Raw;
        model: serializers.Model.Raw;
        openai: serializers.OpenAiConfig.Raw;
        system_message: serializers.SystemMessage.Raw;
    }
}
