/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const AnthropicConfigTopP: core.serialization.Schema<serializers.AnthropicConfigTopP.Raw, ProficientAiApi.AnthropicConfigTopP>;
export declare namespace AnthropicConfigTopP {
    type Raw = number;
}
