/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const GreetingMessage: core.serialization.Schema<serializers.GreetingMessage.Raw, ProficientAiApi.GreetingMessage>;
export declare namespace GreetingMessage {
    type Raw = string;
}
