/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const OpenAiConfigFrequencyPenalty: core.serialization.Schema<serializers.OpenAiConfigFrequencyPenalty.Raw, ProficientAiApi.OpenAiConfigFrequencyPenalty>;
export declare namespace OpenAiConfigFrequencyPenalty {
    type Raw = number;
}
