/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as ProficientAiApi from "../../../../api";
import * as core from "../../../../core";
export declare const OpenAiConfigPresencePenalty: core.serialization.Schema<serializers.OpenAiConfigPresencePenalty.Raw, ProficientAiApi.OpenAiConfigPresencePenalty>;
export declare namespace OpenAiConfigPresencePenalty {
    type Raw = number;
}
