/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Proficient from "../../../..";
export interface ListInteractionsRequest {
    agentId?: Proficient.AgentId;
    limit?: Proficient.PaginationLimit;
    startingAfter?: Proficient.PaginationStartingAfter;
}
