/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Proficient from "../../..";
export declare namespace Messages {
    interface Options {
        environment?: core.Supplier<environments.ProficientEnvironment | string>;
        secretKey?: core.Supplier<string | undefined>;
        apiKey?: core.Supplier<string | undefined>;
        userExternalId?: core.Supplier<string | undefined>;
        userHmac?: core.Supplier<string | undefined>;
    }
}
export declare class Messages {
    protected readonly options: Messages.Options;
    constructor(options: Messages.Options);
    /**
     * Returns a list of all messages in the specified interaction.
     * @throws {@link Proficient.ForbiddenError}
     * @throws {@link Proficient.ResourceNotFoundError}
     * @throws {@link Proficient.InternalError}
     */
    list(request: Proficient.ListMessagesRequest): Promise<Proficient.MessagesList>;
    /**
     * Retrieves the message with the given ID.
     * @throws {@link Proficient.ForbiddenError}
     * @throws {@link Proficient.ResourceNotFoundError}
     * @throws {@link Proficient.InternalError}
     */
    get(messageId: Proficient.MessageId): Promise<Proficient.Message>;
    /**
     * Creates a new `Message` in a given `Interaction`
     * @throws {@link Proficient.ForbiddenError}
     * @throws {@link Proficient.ResourceNotFoundError}
     * @throws {@link Proficient.ConflictError}
     * @throws {@link Proficient.InternalError}
     */
    create(request: Proficient.MessageCreateParams): Promise<Proficient.Message>;
    /**
     * Requests a reply from the `Agent` to a given `Message`.
     * @throws {@link Proficient.ForbiddenError}
     * @throws {@link Proficient.ResourceNotFoundError}
     * @throws {@link Proficient.ConflictError}
     * @throws {@link Proficient.InternalError}
     */
    ask(messageId: Proficient.MessageId, request: Proficient.MessageAskParams): Promise<Proficient.Message>;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
